spring:
  application:
    name: java-21-springboot-template
  
  datasource:
    url: jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres?sslmode=require&reWriteBatchedInserts=true
    username: postgres.zxxvfsesezawckyrchnu
    password: loay0636561440   # vervang door jouw echte wachtwoord
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    user:
      name: admin
      password: admin

supabase:
  url: ${SUPABASE_URL:https://xxxxx.supabase.co}
  anon-key: ${SUPABASE_ANON_KEY:your-anon-key-here}

server:
  port: 8080
